[versions]
agp = "8.12.3"
coreKtx = "1.18.0"
kotlin = "2.0.21"
opencv = "4.13.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
opencv-android-ximgproc = { module = "org.opencv:opencv-android-ximgproc", version.ref = "opencv" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
