[versions]
agp = "8.12.3"
coreKtx = "1.18.0"
junit = "4.13.2"
mockk = "1.13.13"
kotlin = "2.3.21"
kotlinCsv = "2.0.0"
opencv = "4.13.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotlin-csv = { module = "com.jsoizo:kotlin-csv", version.ref = "kotlinCsv" }
opencv-android-ximgproc = { module = "org.opencv:opencv-android-ximgproc", version.ref = "opencv" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
